export const baseLocalEng = {
  Components: {
    add: 'Add',
  },
  IntroPage: {
    mainText: 'Selamat Datang di McDonald',
    subText:
      'Makin hemat dan praktis peran lewat aplikasi, banyak menu, banyak promo, nggakperlu keluar rumah!',
    btnText: 'Pesan Sekarang',
  },
  SignIn: {
    welcomeMsg: "Welcome To McDonald's",
    loginMsg: 'Login to continue',
    email: 'Email',
    emailPlaceHolder: 'Enter your email',
    password: 'Password',
    passwordPlaceHolder: 'Enter your password',
    signIn: 'Sign In',
    noAccountMsg: "Didn't have an account?",
    signUp: ' Sign Up',
    validationError: 'Validation Error',
    emailNotFound: 'Email not found',
    incorrectPassword: 'Incorrect Password',
    checkEmailAndPassword: 'Check Email and Password',
  },
  SignUp: {
    signUpMsg: 'Register to continue',
    name: 'Name',
    namePlaceHolder: 'Enter your name',
    phone: 'Phone Number',
    phonePlaceHolder: 'Enter your phone number',
    confirmPassword: 'Confirm Password',
    gender: 'Gender',
    male: 'Male',
    female: 'Female',
    signUp: 'Sign Up',
    accountExistMsg: 'Already have an account?',
    signIn: ' Sign In',
    error: 'Error',
    accountExistAlertMsg: 'User Already Exists!! Please Login',
    cancel: 'Cancel',
    ok: 'OK',
  },
  HomePage: {
    search: 'Search',
    selectLocation: 'Select Location',
    category: 'Kategori',
    specialOffer: 'Special Offer',
    SpecialOfferBtn: 'Lihat Semua',
  },
  specialOffer: {
    header: 'Special Offer',
  },
  itemDetails: {
    description:
      'Lebih Extra dan Lebih Nikmat dengan Beef Rasher diantara dua lapis daging sapi, saus spesial, selada, keju, acar timun, bawang yang diapit roti wijen.',
    optionalHeader: 'Tambahkan Catatan',
    optional: ' (Optional)',
    textInputPlaceHolder: 'Cth. Tanpa keju dan tomat',
    btnText: 'Masukkan Keranjang',
  },
  cartPage: {
    title: 'Pesananmu',
    totalItem: 'Total Item',
    biayaPengiriman: 'Biaya Pengiriman',
    totalBiaya: 'Total Biaya',
    gratis: 'GRATIS',
    btnText: 'Bayar',
    orderConfirmationTitle: 'Order Confirmation',
    orderConfirmationMsg: 'Your order has been successfully placed!',
    ok: 'OK',
    noItem: 'No Item in the cart !!!',
  },
  profilePage: {
    name: 'Name',
    email: 'Email',
    gender: 'Gender',
    phone: 'Phone Number',
    logout: 'Logout',
    proflie: 'Profile',
    previousOrders: 'Previous Orders',
    date: 'Date',
    time: 'Time',
    totalItems: 'Total Items',
    totalPrice: 'Total Price',
    itemsOrdered: 'Items Ordered',
    changeProfilePicture: 'Change Profile Picture',
    chooseOption: 'Choose an option',
    camera: 'Camera',
    gallery: 'Gallery',
  },
  updateProfileDetailsPage: {
    error: 'Error',
    nameRequired: 'Name is required',
    phoneRequired: 'Phone number is required',
    validPhone: 'Please enter a valid phone number',
    update: 'Update',
  },
};
